//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address already exists for the user with all same fields. Please check..
        /// </summary>
        public static string AddressAlreadyExistsForUser {
            get {
                return ResourceManager.GetString("AddressAlreadyExistsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string CaptionConfirm {
            get {
                return ResourceManager.GetString("CaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string CaptionInformation {
            get {
                return ResourceManager.GetString("CaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string CaptionWarning {
            get {
                return ResourceManager.GetString("CaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/View.
        /// </summary>
        public static string EditView {
            get {
                return ResourceManager.GetString("EditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter some values to search.
        /// </summary>
        public static string EnterValueToSearch {
            get {
                return ResourceManager.GetString("EnterValueToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name....
        /// </summary>
        public static string FirstNamePlaceholderValue {
            get {
                return ResourceManager.GetString("FirstNamePlaceholderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured. Please try again after sometime. Error has been reported to Administrator..
        /// </summary>
        public static string GenericExceptionMessage {
            get {
                return ResourceManager.GetString("GenericExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Country.
        /// </summary>
        public static string InvalidCountry {
            get {
                return ResourceManager.GetString("InvalidCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name....
        /// </summary>
        public static string LastNamePlaceholderValue {
            get {
                return ResourceManager.GetString("LastNamePlaceholderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers are not allowed.
        /// </summary>
        public static string NoNumbersAllowed {
            get {
                return ResourceManager.GetString("NoNumbersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Characters and Symbols are not allowed.
        /// </summary>
        public static string NoSpecialChactersAndSymbols {
            get {
                return ResourceManager.GetString("NoSpecialChactersAndSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found in system with following First Name &quot;{0}&quot; and Last Name &quot;{1}&quot;.
        /// </summary>
        public static string NoUsersFoundWithFirstNameLastName {
            get {
                return ResourceManager.GetString("NoUsersFoundWithFirstNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved successfully.
        /// </summary>
        public static string RecordSavedSuccessfully {
            get {
                return ResourceManager.GetString("RecordSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wan to delete this item?.
        /// </summary>
        public static string SureToDelete {
            get {
                return ResourceManager.GetString("SureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists in database with same First and Last Name. Please use different First or Last Name..
        /// </summary>
        public static string UserExistsWithName {
            get {
                return ResourceManager.GetString("UserExistsWithName", resourceCulture);
            }
        }
    }
}
